import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-p1CmZkS6GJZr38S0sIb69eUjM8w8VxBuW1piUv2NHYAHtwfB8RyM+c3j3eTfA2nQpL+9VjDndR7Kfk2QwD2zlw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        style={{ background: "black", color: "white" }}
        className={`${geistSans.variable} ${geistMono.variable} antialiase`}
      >
        {children}
      </body>
    </html>
  );
}
